from core.nklite.base.button import Button

# This file was automatically generated by tools/button_extract.py.
# Do not modify it manually.

BTN_BATCH_SELL = Button(area=(0, 0, 137, 43), color=(173, 194, 49), button=(0, 0, 137, 43), file='templates/btn/btn_batch_sell.png', name='btn_batch_sell')  # 批量出售
BTN_BUG = Button(area=(332, 683, 372, 717), color=(152, 125, 112), button=(332, 683, 372, 717), file='templates/btn/btn_bug.png', name='btn_bug')  # 一键除虫
BTN_BUY_CONFIRM = Button(area=(0, 0, 135, 41), color=(165, 191, 23), button=(0, 0, 135, 41), file='templates/btn/btn_buy_confirm.png', name='btn_buy_confirm')  # 购买确认
BTN_BUY_MAX = Button(area=(0, 0, 44, 48), color=(204, 141, 91), button=(0, 0, 44, 48), file='templates/btn/btn_buy_max.png', name='btn_buy_max')  # 最大购买
BTN_CLAIM = Button(area=(0, 0, 174, 62), color=(182, 204, 62), button=(0, 0, 174, 62), file='templates/btn/btn_claim.png', name='btn_claim')  # 领取
BTN_CLOSE = Button(area=(493, 54, 527, 88), color=(236, 191, 165), button=(493, 54, 527, 88), file='templates/btn/btn_close.png', name='btn_close')  # 关闭
BTN_CONFIRM = Button(area=(0, 0, 135, 41), color=(165, 191, 23), button=(0, 0, 135, 41), file='templates/btn/btn_confirm.png', name='btn_confirm')  # 确认
BTN_EXPAND = Button(area=(0, 0, 39, 19), color=(194, 127, 63), button=(0, 0, 39, 19), file='templates/btn/btn_expand.png', name='btn_expand')  # 扩建
BTN_EXPAND_CONFIRM = Button(area=(0, 0, 133, 41), color=(165, 191, 23), button=(0, 0, 133, 41), file='templates/btn/btn_expand_confirm.png', name='btn_expand_confirm')
BTN_EXPAND_DIRECT_CONFIRM = Button(area=(0, 0, 200, 66), color=(187, 202, 64), button=(0, 0, 200, 66), file='templates/btn/btn_expand_direct_confirm.png', name='btn_expand_direct_confirm')
BTN_FERTILIZE_POPUP = Button(area=(0, 0, 63, 55), color=(199, 152, 86), button=(0, 0, 63, 55), file='templates/btn/btn_fertilize_popup.png', name='btn_fertilize_popup')
BTN_FRIEND_HELP = Button(area=(0, 0, 162, 73), color=(224, 221, 180), button=(0, 0, 162, 73), file='templates/btn/btn_friend_help.png', name='btn_friend_help')  # 好友求助
BTN_HARVEST = Button(area=(0, 0, 58, 60), color=(205, 158, 113), button=(0, 0, 58, 60), file='templates/btn/btn_harvest.png', name='btn_harvest')  # 一键收获
BTN_HOME = Button(area=(0, 0, 78, 74), color=(155, 133, 67), button=(0, 0, 78, 74), file='templates/btn/btn_home.png', name='btn_home')  # 回家
BTN_SELL = Button(area=(0, 0, 137, 43), color=(235, 179, 26), button=(0, 0, 137, 43), file='templates/btn/btn_sell.png', name='btn_sell')
BTN_WATER = Button(area=(160, 683, 200, 717), color=(167, 157, 156), button=(160, 683, 200, 717), file='templates/btn/btn_water.png', name='btn_water')  # 一键浇水
BTN_WEED = Button(area=(246, 683, 286, 717), color=(161, 158, 110), button=(246, 683, 286, 717), file='templates/btn/btn_weed.png', name='btn_weed')  # 一键除草
FRIEND_CHECK = Button(area=(241, 69, 299, 98), color=(225, 186, 159), button=(241, 69, 299, 98), file='templates/ui/friend_check.png', name='friend_check')
ICON_MATURE = Button(area=(0, 0, 36, 37), color=(195, 205, 100), button=(0, 0, 36, 37), file='templates/icon/icon_mature.png', name='icon_mature')  # 成熟图标
LAND_EMPTY = Button(area=(0, 0, 30, 25), color=(183, 135, 77), button=(0, 0, 30, 25), file='templates/land/land_empty.png', name='land_empty')  # 空地
LAND_EMPTY_2 = Button(area=(0, 0, 47, 23), color=(186, 139, 79), button=(0, 0, 47, 23), file='templates/land/land_empty_2.png', name='land_empty_2')  # 空地2
LAND_EMPTY_3 = Button(area=(0, 0, 33, 26), color=(184, 137, 78), button=(0, 0, 33, 26), file='templates/land/land_empty_3.png', name='land_empty_3')  # 空地3
MAIN_GOTO_FRIEND = Button(area=(448, 863, 493, 894), color=(221, 187, 122), button=(448, 863, 493, 894), file='templates/ui/main_goto_friend.png', name='main_goto_friend')
MAIN_GOTO_MALL = Button(area=(474, 164, 505, 189), color=(184, 182, 97), button=(474, 164, 505, 189), file='templates/ui/main_goto_mall.png', name='main_goto_mall')
MAIN_GOTO_MENU = Button(area=(32, 300, 49, 319), color=(229, 191, 127), button=(32, 300, 49, 319), file='templates/ui/main_goto_menu.png', name='main_goto_menu')
MAIN_GOTO_PET = Button(area=(221, 861, 270, 895), color=(197, 174, 169), button=(221, 861, 270, 895), file='templates/ui/main_goto_pet.png', name='main_goto_pet')
MAIN_GOTO_SHARE = Button(area=(34, 160, 59, 183), color=(205, 156, 99), button=(34, 160, 59, 183), file='templates/ui/main_goto_share.png', name='main_goto_share')
MAIN_GOTO_SHOP = Button(area=(126, 861, 175, 895), color=(222, 183, 98), button=(126, 861, 175, 895), file='templates/ui/main_goto_shop.png', name='main_goto_shop')
MAIN_GOTO_TASK = Button(area=(34, 782, 64, 812), color=(222, 190, 149), button=(34, 782, 64, 812), file='templates/ui/main_goto_task.png', name='main_goto_task')
MAIN_GOTO_WAREHOUSE = Button(area=(30, 861, 79, 895), color=(217, 166, 99), button=(30, 861, 79, 895), file='templates/ui/main_goto_warehouse.png', name='main_goto_warehouse')
MAIN_GOTO_WIKI = Button(area=(319, 868, 366, 895), color=(218, 163, 130), button=(319, 868, 366, 895), file='templates/ui/main_goto_wiki.png', name='main_goto_wiki')
MALL_CHECK = Button(area=(117, 83, 174, 112), color=(193, 156, 137), button=(117, 83, 174, 112), file='templates/ui/mall_check.png', name='mall_check')
MALL_GOTO_MAIN = Button(area=(44, 93, 82, 122), color=(230, 187, 117), button=(44, 93, 82, 122), file='templates/ui/mall_goto_main.png', name='mall_goto_main')
MENU_GOTO_MAIN = Button(area=(31, 300, 51, 319), color=(244, 210, 136), button=(31, 300, 51, 319), file='templates/ui/menu_goto_main.png', name='menu_goto_main')
PET_CHECK = Button(area=(241, 77, 294, 105), color=(232, 199, 181), button=(241, 77, 294, 105), file='templates/ui/pet_check.png', name='pet_check')
SETTING_CHECK = Button(area=(31, 607, 53, 632), color=(227, 183, 122), button=(31, 607, 53, 632), file='templates/ui/setting_check.png', name='setting_check')
SHOP_CHECK = Button(area=(241, 85, 298, 113), color=(225, 191, 168), button=(241, 85, 298, 113), file='templates/ui/shop_check.png', name='shop_check')
TASK_CHECK = Button(area=(242, 87, 298, 115), color=(224, 188, 165), button=(242, 87, 298, 115), file='templates/ui/task_check.png', name='task_check')
WAREHOUSE_CHECK = Button(area=(242, 70, 298, 98), color=(226, 188, 168), button=(242, 70, 298, 98), file='templates/ui/warehouse_check.png', name='warehouse_check')
WIKI_CHECK = Button(area=(244, 72, 298, 98), color=(233, 206, 186), button=(244, 72, 298, 98), file='templates/ui/wiki_check.png', name='wiki_check')

ASSET_NAME_TO_CONST = {
    'btn_batch_sell': BTN_BATCH_SELL,
    'btn_bug': BTN_BUG,
    'btn_buy_confirm': BTN_BUY_CONFIRM,
    'btn_buy_max': BTN_BUY_MAX,
    'btn_claim': BTN_CLAIM,
    'btn_close': BTN_CLOSE,
    'btn_confirm': BTN_CONFIRM,
    'btn_expand': BTN_EXPAND,
    'btn_expand_confirm': BTN_EXPAND_CONFIRM,
    'btn_expand_direct_confirm': BTN_EXPAND_DIRECT_CONFIRM,
    'btn_fertilize_popup': BTN_FERTILIZE_POPUP,
    'btn_friend_help': BTN_FRIEND_HELP,
    'btn_harvest': BTN_HARVEST,
    'btn_home': BTN_HOME,
    'btn_sell': BTN_SELL,
    'btn_water': BTN_WATER,
    'btn_weed': BTN_WEED,
    'friend_check': FRIEND_CHECK,
    'icon_mature': ICON_MATURE,
    'land_empty': LAND_EMPTY,
    'land_empty_2': LAND_EMPTY_2,
    'land_empty_3': LAND_EMPTY_3,
    'main_goto_friend': MAIN_GOTO_FRIEND,
    'main_goto_mall': MAIN_GOTO_MALL,
    'main_goto_menu': MAIN_GOTO_MENU,
    'main_goto_pet': MAIN_GOTO_PET,
    'main_goto_share': MAIN_GOTO_SHARE,
    'main_goto_shop': MAIN_GOTO_SHOP,
    'main_goto_task': MAIN_GOTO_TASK,
    'main_goto_warehouse': MAIN_GOTO_WAREHOUSE,
    'main_goto_wiki': MAIN_GOTO_WIKI,
    'mall_check': MALL_CHECK,
    'mall_goto_main': MALL_GOTO_MAIN,
    'menu_goto_main': MENU_GOTO_MAIN,
    'pet_check': PET_CHECK,
    'setting_check': SETTING_CHECK,
    'shop_check': SHOP_CHECK,
    'task_check': TASK_CHECK,
    'warehouse_check': WAREHOUSE_CHECK,
    'wiki_check': WIKI_CHECK,
}
