from core.base.button import Button

# This file was automatically generated by tools/button_extract.py.
# Do not modify it manually.

BTN_BATCH_SELL = Button(area={'qq': (0, 0, 137, 43), 'wechat': (0, 0, 137, 43)}, color={'qq': (173, 194, 49), 'wechat': (173, 194, 49)}, button={'qq': (0, 0, 137, 43), 'wechat': (0, 0, 137, 43)}, file={'qq': 'templates/qq/btn/btn_batch_sell.png', 'wechat': 'templates/qq/btn/btn_batch_sell.png'}, name='btn_batch_sell')  # 批量出售
BTN_BUG = Button(area={'qq': (332, 683, 372, 717), 'wechat': (332, 683, 372, 717)}, color={'qq': (152, 125, 112), 'wechat': (152, 125, 112)}, button={'qq': (332, 683, 372, 717), 'wechat': (332, 683, 372, 717)}, file={'qq': 'templates/qq/btn/btn_bug.png', 'wechat': 'templates/qq/btn/btn_bug.png'}, name='btn_bug')  # 一键除虫
BTN_BUY_CONFIRM = Button(area={'qq': (0, 0, 135, 41), 'wechat': (0, 0, 135, 41)}, color={'qq': (165, 191, 23), 'wechat': (165, 191, 23)}, button={'qq': (0, 0, 135, 41), 'wechat': (0, 0, 135, 41)}, file={'qq': 'templates/qq/btn/btn_buy_confirm.png', 'wechat': 'templates/qq/btn/btn_buy_confirm.png'}, name='btn_buy_confirm')  # 购买确认
BTN_BUY_MAX = Button(area={'qq': (0, 0, 44, 48), 'wechat': (0, 0, 44, 48)}, color={'qq': (204, 141, 91), 'wechat': (204, 141, 91)}, button={'qq': (0, 0, 44, 48), 'wechat': (0, 0, 44, 48)}, file={'qq': 'templates/qq/btn/btn_buy_max.png', 'wechat': 'templates/qq/btn/btn_buy_max.png'}, name='btn_buy_max')  # 最大购买
BTN_CLAIM = Button(area={'qq': (0, 0, 174, 62), 'wechat': (0, 0, 174, 62)}, color={'qq': (182, 204, 62), 'wechat': (182, 204, 62)}, button={'qq': (0, 0, 174, 62), 'wechat': (0, 0, 174, 62)}, file={'qq': 'templates/qq/btn/btn_claim.png', 'wechat': 'templates/qq/btn/btn_claim.png'}, name='btn_claim')  # 领取
BTN_CLOSE = Button(area={'qq': (493, 54, 527, 88), 'wechat': (493, 54, 527, 88)}, color={'qq': (236, 191, 165), 'wechat': (236, 191, 165)}, button={'qq': (493, 54, 527, 88), 'wechat': (493, 54, 527, 88)}, file={'qq': 'templates/qq/btn/btn_close.png', 'wechat': 'templates/qq/btn/btn_close.png'}, name='btn_close')  # 关闭
BTN_CONFIRM = Button(area={'qq': (0, 0, 135, 41), 'wechat': (0, 0, 135, 41)}, color={'qq': (165, 191, 23), 'wechat': (165, 191, 23)}, button={'qq': (0, 0, 135, 41), 'wechat': (0, 0, 135, 41)}, file={'qq': 'templates/qq/btn/btn_confirm.png', 'wechat': 'templates/qq/btn/btn_confirm.png'}, name='btn_confirm')  # 确认
BTN_EXPAND = Button(area={'qq': (0, 0, 39, 19), 'wechat': (0, 0, 39, 19)}, color={'qq': (194, 127, 63), 'wechat': (194, 127, 63)}, button={'qq': (0, 0, 39, 19), 'wechat': (0, 0, 39, 19)}, file={'qq': 'templates/qq/btn/btn_expand.png', 'wechat': 'templates/qq/btn/btn_expand.png'}, name='btn_expand')  # 扩建
BTN_EXPAND_CONFIRM = Button(area={'qq': (0, 0, 133, 41), 'wechat': (0, 0, 133, 41)}, color={'qq': (165, 191, 23), 'wechat': (165, 191, 23)}, button={'qq': (0, 0, 133, 41), 'wechat': (0, 0, 133, 41)}, file={'qq': 'templates/qq/btn/btn_expand_confirm.png', 'wechat': 'templates/qq/btn/btn_expand_confirm.png'}, name='btn_expand_confirm')
BTN_EXPAND_DIRECT_CONFIRM = Button(area={'qq': (0, 0, 200, 66), 'wechat': (0, 0, 200, 66)}, color={'qq': (187, 202, 64), 'wechat': (187, 202, 64)}, button={'qq': (0, 0, 200, 66), 'wechat': (0, 0, 200, 66)}, file={'qq': 'templates/qq/btn/btn_expand_direct_confirm.png', 'wechat': 'templates/qq/btn/btn_expand_direct_confirm.png'}, name='btn_expand_direct_confirm')
BTN_FERTILIZE_POPUP = Button(area={'qq': (0, 0, 63, 55), 'wechat': (0, 0, 63, 55)}, color={'qq': (199, 152, 86), 'wechat': (199, 152, 86)}, button={'qq': (0, 0, 63, 55), 'wechat': (0, 0, 63, 55)}, file={'qq': 'templates/qq/btn/btn_fertilize_popup.png', 'wechat': 'templates/qq/btn/btn_fertilize_popup.png'}, name='btn_fertilize_popup')
BTN_FRIEND_HELP = Button(area={'qq': (0, 0, 162, 73), 'wechat': (0, 0, 162, 73)}, color={'qq': (224, 221, 180), 'wechat': (224, 221, 180)}, button={'qq': (0, 0, 162, 73), 'wechat': (0, 0, 162, 73)}, file={'qq': 'templates/qq/btn/btn_friend_help.png', 'wechat': 'templates/qq/btn/btn_friend_help.png'}, name='btn_friend_help')  # 好友求助
BTN_HARVEST = Button(area={'qq': (246, 688, 287, 720), 'wechat': (246, 688, 287, 720)}, color={'qq': (221, 169, 139), 'wechat': (221, 169, 139)}, button={'qq': (246, 688, 287, 720), 'wechat': (246, 688, 287, 720)}, file={'qq': 'templates/qq/btn/btn_harvest.png', 'wechat': 'templates/qq/btn/btn_harvest.png'}, name='btn_harvest')  # 一键收获
BTN_HOME = Button(area={'qq': (0, 0, 78, 74), 'wechat': (0, 0, 78, 74)}, color={'qq': (155, 133, 67), 'wechat': (155, 133, 67)}, button={'qq': (0, 0, 78, 74), 'wechat': (0, 0, 78, 74)}, file={'qq': 'templates/qq/btn/btn_home.png', 'wechat': 'templates/qq/btn/btn_home.png'}, name='btn_home')  # 回家
BTN_MATURE = Button(area={'qq': (261, 457, 278, 479), 'wechat': (261, 457, 278, 479)}, color={'qq': (201, 181, 78), 'wechat': (201, 181, 78)}, button={'qq': (261, 457, 278, 479), 'wechat': (261, 457, 278, 479)}, file={'qq': 'templates/qq/btn/btn_mature.png', 'wechat': 'templates/qq/btn/btn_mature.png'}, name='btn_mature')
BTN_SELL = Button(area={'qq': (0, 0, 137, 43), 'wechat': (0, 0, 137, 43)}, color={'qq': (235, 179, 26), 'wechat': (235, 179, 26)}, button={'qq': (0, 0, 137, 43), 'wechat': (0, 0, 137, 43)}, file={'qq': 'templates/qq/btn/btn_sell.png', 'wechat': 'templates/qq/btn/btn_sell.png'}, name='btn_sell')
BTN_WATER = Button(area={'qq': (160, 683, 200, 717), 'wechat': (160, 683, 200, 717)}, color={'qq': (167, 157, 156), 'wechat': (167, 157, 156)}, button={'qq': (160, 683, 200, 717), 'wechat': (160, 683, 200, 717)}, file={'qq': 'templates/qq/btn/btn_water.png', 'wechat': 'templates/qq/btn/btn_water.png'}, name='btn_water')  # 一键浇水
BTN_WEED = Button(area={'qq': (246, 683, 286, 717), 'wechat': (246, 683, 286, 717)}, color={'qq': (161, 158, 110), 'wechat': (161, 158, 110)}, button={'qq': (246, 683, 286, 717), 'wechat': (246, 683, 286, 717)}, file={'qq': 'templates/qq/btn/btn_weed.png', 'wechat': 'templates/qq/btn/btn_weed.png'}, name='btn_weed')  # 一键除草
FRIEND_CHECK = Button(area={'qq': (241, 69, 299, 98), 'wechat': (241, 69, 299, 98)}, color={'qq': (225, 186, 159), 'wechat': (225, 186, 159)}, button={'qq': (241, 69, 299, 98), 'wechat': (241, 69, 299, 98)}, file={'qq': 'templates/qq/ui/friend_check.png', 'wechat': 'templates/qq/ui/friend_check.png'}, name='friend_check')
LAND_EMPTY = Button(area={'qq': (0, 0, 30, 25), 'wechat': (0, 0, 30, 25)}, color={'qq': (183, 135, 77), 'wechat': (183, 135, 77)}, button={'qq': (0, 0, 30, 25), 'wechat': (0, 0, 30, 25)}, file={'qq': 'templates/qq/land/land_empty.png', 'wechat': 'templates/qq/land/land_empty.png'}, name='land_empty')  # 空地
LAND_EMPTY_2 = Button(area={'qq': (0, 0, 47, 23), 'wechat': (0, 0, 47, 23)}, color={'qq': (186, 139, 79), 'wechat': (186, 139, 79)}, button={'qq': (0, 0, 47, 23), 'wechat': (0, 0, 47, 23)}, file={'qq': 'templates/qq/land/land_empty_2.png', 'wechat': 'templates/qq/land/land_empty_2.png'}, name='land_empty_2')  # 空地2
LAND_EMPTY_3 = Button(area={'qq': (0, 0, 33, 26), 'wechat': (0, 0, 33, 26)}, color={'qq': (184, 137, 78), 'wechat': (184, 137, 78)}, button={'qq': (0, 0, 33, 26), 'wechat': (0, 0, 33, 26)}, file={'qq': 'templates/qq/land/land_empty_3.png', 'wechat': 'templates/qq/land/land_empty_3.png'}, name='land_empty_3')  # 空地3
MAIN_GOTO_FRIEND = Button(area={'qq': (448, 863, 493, 894), 'wechat': (448, 863, 493, 894)}, color={'qq': (221, 187, 122), 'wechat': (221, 187, 122)}, button={'qq': (448, 863, 493, 894), 'wechat': (448, 863, 493, 894)}, file={'qq': 'templates/qq/ui/main_goto_friend.png', 'wechat': 'templates/qq/ui/main_goto_friend.png'}, name='main_goto_friend')
MAIN_GOTO_MALL = Button(area={'qq': (474, 164, 505, 189), 'wechat': (474, 164, 505, 189)}, color={'qq': (184, 182, 97), 'wechat': (184, 182, 97)}, button={'qq': (474, 164, 505, 189), 'wechat': (474, 164, 505, 189)}, file={'qq': 'templates/qq/ui/main_goto_mall.png', 'wechat': 'templates/qq/ui/main_goto_mall.png'}, name='main_goto_mall')
MAIN_GOTO_MENU = Button(area={'qq': (32, 300, 49, 319), 'wechat': (32, 300, 49, 319)}, color={'qq': (229, 191, 127), 'wechat': (229, 191, 127)}, button={'qq': (32, 300, 49, 319), 'wechat': (32, 300, 49, 319)}, file={'qq': 'templates/qq/ui/main_goto_menu.png', 'wechat': 'templates/qq/ui/main_goto_menu.png'}, name='main_goto_menu')
MAIN_GOTO_PET = Button(area={'qq': (221, 861, 270, 895), 'wechat': (221, 861, 270, 895)}, color={'qq': (197, 174, 169), 'wechat': (197, 174, 169)}, button={'qq': (221, 861, 270, 895), 'wechat': (221, 861, 270, 895)}, file={'qq': 'templates/qq/ui/main_goto_pet.png', 'wechat': 'templates/qq/ui/main_goto_pet.png'}, name='main_goto_pet')
MAIN_GOTO_SHARE = Button(area={'qq': (34, 160, 59, 183), 'wechat': (34, 160, 59, 183)}, color={'qq': (205, 156, 99), 'wechat': (205, 156, 99)}, button={'qq': (34, 160, 59, 183), 'wechat': (34, 160, 59, 183)}, file={'qq': 'templates/qq/ui/main_goto_share.png', 'wechat': 'templates/qq/ui/main_goto_share.png'}, name='main_goto_share')
MAIN_GOTO_SHOP = Button(area={'qq': (126, 861, 175, 895), 'wechat': (126, 861, 175, 895)}, color={'qq': (222, 183, 98), 'wechat': (222, 183, 98)}, button={'qq': (126, 861, 175, 895), 'wechat': (126, 861, 175, 895)}, file={'qq': 'templates/qq/ui/main_goto_shop.png', 'wechat': 'templates/qq/ui/main_goto_shop.png'}, name='main_goto_shop')
MAIN_GOTO_TASK = Button(area={'qq': (34, 782, 64, 812), 'wechat': (34, 782, 64, 812)}, color={'qq': (222, 190, 149), 'wechat': (222, 190, 149)}, button={'qq': (34, 782, 64, 812), 'wechat': (34, 782, 64, 812)}, file={'qq': 'templates/qq/ui/main_goto_task.png', 'wechat': 'templates/qq/ui/main_goto_task.png'}, name='main_goto_task')
MAIN_GOTO_WAREHOUSE = Button(area={'qq': (30, 861, 79, 895), 'wechat': (30, 861, 79, 895)}, color={'qq': (217, 166, 99), 'wechat': (217, 166, 99)}, button={'qq': (30, 861, 79, 895), 'wechat': (30, 861, 79, 895)}, file={'qq': 'templates/qq/ui/main_goto_warehouse.png', 'wechat': 'templates/qq/ui/main_goto_warehouse.png'}, name='main_goto_warehouse')
MAIN_GOTO_WIKI = Button(area={'qq': (319, 868, 366, 895), 'wechat': (319, 868, 366, 895)}, color={'qq': (218, 163, 130), 'wechat': (218, 163, 130)}, button={'qq': (319, 868, 366, 895), 'wechat': (319, 868, 366, 895)}, file={'qq': 'templates/qq/ui/main_goto_wiki.png', 'wechat': 'templates/qq/ui/main_goto_wiki.png'}, name='main_goto_wiki')
MALL_CHECK = Button(area={'qq': (117, 83, 174, 112), 'wechat': (117, 83, 174, 112)}, color={'qq': (193, 156, 137), 'wechat': (193, 156, 137)}, button={'qq': (117, 83, 174, 112), 'wechat': (117, 83, 174, 112)}, file={'qq': 'templates/qq/ui/mall_check.png', 'wechat': 'templates/qq/ui/mall_check.png'}, name='mall_check')
MALL_GOTO_MAIN = Button(area={'qq': (44, 93, 82, 122), 'wechat': (44, 93, 82, 122)}, color={'qq': (230, 187, 117), 'wechat': (230, 187, 117)}, button={'qq': (44, 93, 82, 122), 'wechat': (44, 93, 82, 122)}, file={'qq': 'templates/qq/ui/mall_goto_main.png', 'wechat': 'templates/qq/ui/mall_goto_main.png'}, name='mall_goto_main')
MENU_GOTO_MAIN = Button(area={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, color={'qq': (244, 210, 136), 'wechat': (244, 210, 136)}, button={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, file={'qq': 'templates/qq/ui/menu_goto_main.png', 'wechat': 'templates/qq/ui/menu_goto_main.png'}, name='menu_goto_main')
PET_CHECK = Button(area={'qq': (241, 77, 294, 105), 'wechat': (241, 77, 294, 105)}, color={'qq': (232, 199, 181), 'wechat': (232, 199, 181)}, button={'qq': (241, 77, 294, 105), 'wechat': (241, 77, 294, 105)}, file={'qq': 'templates/qq/ui/pet_check.png', 'wechat': 'templates/qq/ui/pet_check.png'}, name='pet_check')
SETTING_CHECK = Button(area={'qq': (31, 607, 53, 632), 'wechat': (31, 607, 53, 632)}, color={'qq': (227, 183, 122), 'wechat': (227, 183, 122)}, button={'qq': (31, 607, 53, 632), 'wechat': (31, 607, 53, 632)}, file={'qq': 'templates/qq/ui/setting_check.png', 'wechat': 'templates/qq/ui/setting_check.png'}, name='setting_check')
SHOP_CHECK = Button(area={'qq': (241, 85, 298, 113), 'wechat': (241, 85, 298, 113)}, color={'qq': (225, 191, 168), 'wechat': (225, 191, 168)}, button={'qq': (241, 85, 298, 113), 'wechat': (241, 85, 298, 113)}, file={'qq': 'templates/qq/ui/shop_check.png', 'wechat': 'templates/qq/ui/shop_check.png'}, name='shop_check')
TASK_CHECK = Button(area={'qq': (242, 87, 298, 115), 'wechat': (242, 87, 298, 115)}, color={'qq': (224, 188, 165), 'wechat': (224, 188, 165)}, button={'qq': (242, 87, 298, 115), 'wechat': (242, 87, 298, 115)}, file={'qq': 'templates/qq/ui/task_check.png', 'wechat': 'templates/qq/ui/task_check.png'}, name='task_check')
WAREHOUSE_CHECK = Button(area={'qq': (242, 70, 298, 98), 'wechat': (242, 70, 298, 98)}, color={'qq': (226, 188, 168), 'wechat': (226, 188, 168)}, button={'qq': (242, 70, 298, 98), 'wechat': (242, 70, 298, 98)}, file={'qq': 'templates/qq/ui/warehouse_check.png', 'wechat': 'templates/qq/ui/warehouse_check.png'}, name='warehouse_check')
WIKI_CHECK = Button(area={'qq': (244, 72, 298, 98), 'wechat': (244, 72, 298, 98)}, color={'qq': (233, 206, 186), 'wechat': (233, 206, 186)}, button={'qq': (244, 72, 298, 98), 'wechat': (244, 72, 298, 98)}, file={'qq': 'templates/qq/ui/wiki_check.png', 'wechat': 'templates/qq/ui/wiki_check.png'}, name='wiki_check')

ASSET_NAME_TO_CONST = {
    'btn_batch_sell': BTN_BATCH_SELL,
    'btn_bug': BTN_BUG,
    'btn_buy_confirm': BTN_BUY_CONFIRM,
    'btn_buy_max': BTN_BUY_MAX,
    'btn_claim': BTN_CLAIM,
    'btn_close': BTN_CLOSE,
    'btn_confirm': BTN_CONFIRM,
    'btn_expand': BTN_EXPAND,
    'btn_expand_confirm': BTN_EXPAND_CONFIRM,
    'btn_expand_direct_confirm': BTN_EXPAND_DIRECT_CONFIRM,
    'btn_fertilize_popup': BTN_FERTILIZE_POPUP,
    'btn_friend_help': BTN_FRIEND_HELP,
    'btn_harvest': BTN_HARVEST,
    'btn_home': BTN_HOME,
    'btn_mature': BTN_MATURE,
    'btn_sell': BTN_SELL,
    'btn_water': BTN_WATER,
    'btn_weed': BTN_WEED,
    'friend_check': FRIEND_CHECK,
    'land_empty': LAND_EMPTY,
    'land_empty_2': LAND_EMPTY_2,
    'land_empty_3': LAND_EMPTY_3,
    'main_goto_friend': MAIN_GOTO_FRIEND,
    'main_goto_mall': MAIN_GOTO_MALL,
    'main_goto_menu': MAIN_GOTO_MENU,
    'main_goto_pet': MAIN_GOTO_PET,
    'main_goto_share': MAIN_GOTO_SHARE,
    'main_goto_shop': MAIN_GOTO_SHOP,
    'main_goto_task': MAIN_GOTO_TASK,
    'main_goto_warehouse': MAIN_GOTO_WAREHOUSE,
    'main_goto_wiki': MAIN_GOTO_WIKI,
    'mall_check': MALL_CHECK,
    'mall_goto_main': MALL_GOTO_MAIN,
    'menu_goto_main': MENU_GOTO_MAIN,
    'pet_check': PET_CHECK,
    'setting_check': SETTING_CHECK,
    'shop_check': SHOP_CHECK,
    'task_check': TASK_CHECK,
    'warehouse_check': WAREHOUSE_CHECK,
    'wiki_check': WIKI_CHECK,
}
