"""模板提取为 nklite assets（排除 seed）。

参考 NIKKE/dev_tools/button_extract.py 的思路：
- 扫描模板目录
- 提取 bbox/颜色（忽略 alpha，仅按 RGB 非黑像素取 bbox）
- 支持覆盖文件：`xxx.AREA.png` / `xxx.COLOR.png` / `xxx.BUTTON.png`
- 生成可直接 import 的 Button 常量文件
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES_DIR = ROOT / 'templates'
ALIAS_PATH = ROOT / 'configs' / 'button_aliases.json'
OUTPUT_PATH = ROOT / 'core' / 'nklite' / 'ui' / 'assets.py'
OVERRIDE_SUFFIXES = {'AREA', 'COLOR', 'BUTTON'}


HEADER = """from core.nklite.base.button import Button

# This file was automatically generated by tools/button_extract.py.
# Do not modify it manually.
"""


@dataclass
class Item:
    name: str
    file_rel: str
    area: tuple[int, int, int, int]
    color: tuple[int, int, int]
    button: tuple[int, int, int, int]
    alias: str


@dataclass
class SourceBundle:
    base: Path | None = None
    area: Path | None = None
    color: Path | None = None
    button: Path | None = None


def load_aliases() -> dict[str, str]:
    if not ALIAS_PATH.exists():
        return {}
    data = json.loads(ALIAS_PATH.read_text(encoding='utf-8'))
    if not isinstance(data, dict):
        return {}
    out: dict[str, str] = {}
    for key, value in data.items():
        out[str(key)] = str(value)
    return out


def extract_bbox_and_color(image_path: Path) -> tuple[tuple[int, int, int, int], tuple[int, int, int]]:
    img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
    if img is None:
        return (0, 0, 1, 1), (128, 128, 128)

    if img.ndim == 2:
        bgr = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    else:
        # 对齐 NIKKE：忽略 alpha，仅按 RGB 是否非黑计算 bbox。
        bgr = img[:, :, :3]

    mask = np.any(bgr > 0, axis=2)

    ys, xs = np.where(mask)
    if len(xs) == 0 or len(ys) == 0:
        h, w = bgr.shape[:2]
        return (0, 0, max(1, w), max(1, h)), (128, 128, 128)

    x1 = int(xs.min())
    y1 = int(ys.min())
    x2 = int(xs.max() + 1)
    y2 = int(ys.max() + 1)

    roi = bgr[y1:y2, x1:x2]
    if roi.size == 0:
        mean_rgb = (128, 128, 128)
    else:
        mean_bgr = roi.mean(axis=(0, 1))
        mean_rgb = (int(round(mean_bgr[2])), int(round(mean_bgr[1])), int(round(mean_bgr[0])))
    return (x1, y1, x2, y2), mean_rgb


def image_wh(image_path: Path) -> tuple[int, int] | None:
    img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
    if img is None:
        return None
    h, w = img.shape[:2]
    return int(w), int(h)


def to_const_name(template_name: str) -> str:
    if template_name.startswith('btn_'):
        return 'BTN_' + template_name[4:].upper()
    if template_name.startswith('icon_'):
        return 'ICON_' + template_name[5:].upper()
    if template_name.startswith('land_'):
        return 'LAND_' + template_name[5:].upper()
    safe = ''.join(ch if ch.isalnum() else '_' for ch in template_name).upper()
    return safe


def iter_template_files() -> list[Path]:
    out: list[Path] = []
    for p in TEMPLATES_DIR.rglob('*.png'):
        rel = p.relative_to(TEMPLATES_DIR).as_posix()
        if rel.startswith('seed/'):
            continue
        out.append(p)
    return sorted(out)


def parse_template_name(path: Path) -> tuple[str, str]:
    stem = path.stem
    if '.' not in stem:
        return stem, 'BASE'
    base, suffix = stem.rsplit('.', 1)
    suffix = suffix.upper()
    if suffix in OVERRIDE_SUFFIXES:
        return base, suffix
    return stem, 'BASE'


def collect_sources() -> dict[str, SourceBundle]:
    bundles: dict[str, SourceBundle] = {}
    for path in iter_template_files():
        name, kind = parse_template_name(path)
        bundle = bundles.setdefault(name, SourceBundle())
        if kind == 'BASE':
            if bundle.base is not None and bundle.base != path:
                print(f'[button_extract] duplicate base ignored: {path}')
            else:
                bundle.base = path
            continue
        key = kind.lower()
        current = getattr(bundle, key)
        if current is not None and current != path:
            print(f'[button_extract] duplicate {kind} ignored: {path}')
            continue
        setattr(bundle, key, path)
    return bundles


def build_items() -> list[Item]:
    alias_by_name = load_aliases()
    bundles = collect_sources()
    items: list[Item] = []
    for name in sorted(bundles):
        bundle = bundles[name]
        if bundle.base is None:
            print(f'[button_extract] missing base image, skipped: {name}')
            continue

        rel = bundle.base.relative_to(ROOT).as_posix()
        area, color = extract_bbox_and_color(bundle.base)
        button = area

        if bundle.area is not None:
            area, _ = extract_bbox_and_color(bundle.area)
        if bundle.color is not None:
            _, color = extract_bbox_and_color(bundle.color)
        if bundle.button is not None:
            button, _ = extract_bbox_and_color(bundle.button)

        size = image_wh(bundle.base)
        if (
            size is not None
            and bundle.area is None
            and bundle.button is None
            and size[0] >= 300
            and size[1] >= 500
            and area == (0, 0, size[0], size[1])
        ):
            print(f'[button_extract] full-frame bbox: {name} (consider {name}.AREA.png / {name}.BUTTON.png)')

        alias = str(alias_by_name.get(name, '')).strip()
        items.append(
            Item(
                name=name,
                file_rel=rel,
                area=area,
                color=color,
                button=button,
                alias=alias,
            )
        )
    return items


def render(items: list[Item]) -> str:
    lines = [HEADER.rstrip(), '']
    rendered = {}
    for item in items:
        const_name = to_const_name(item.name)
        base = const_name
        idx = 2
        while const_name in rendered:
            const_name = f'{base}_{idx}'
            idx += 1
        rendered[const_name] = item.name

        comment = f'  # {item.alias}' if item.alias else ''
        lines.append(
            f'{const_name} = Button('
            f'area={item.area}, color={item.color}, button={item.button}, '
            f"file='{item.file_rel}', name='{item.name}'"
            f'){comment}'
        )

    lines.append('')
    lines.append('ASSET_NAME_TO_CONST = {')
    for const_name, asset_name in sorted(rendered.items()):
        lines.append(f"    '{asset_name}': {const_name},")
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


def main():
    items = build_items()
    text = render(items)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text, encoding='utf-8')
    print(f'[button_extract] generated: {OUTPUT_PATH} (items={len(items)})')


if __name__ == '__main__':
    main()
